# Default values for api-chart
replicaCount: 6

image:
  repository: nginx
  tag: 1.29.4
  pullPolicy: IfNotPresent

persistence:
  enabled: false

service:
  type: NodePort
  port: 5001
  targetPort: 5001
  nodePort: 30007

app:
  name: api
  label: api

storage:
  pv:
    name: api-pv
    capacity: 10Gi
    accessModes: ReadWriteOnce
    hostPath: /data/api
  pvc:
    name: api-pvc
    storageClassName: ""
    accessModes: ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    mountPath: /app/data
